//Define all the action type here

export const LOAD_MOVIE_SUCCESS = 'LOAD_MOVIE_SUCCESS'  
export const MOVIE_HAS_ERRORED = 'MOVIE_HAS_ERRORED'  
export const MOVIE_IS_LOADING = 'MOVIE_IS_LOADING'
export const LOAD_MOVIE_FILTER = 'LOAD_MOVIE_FILTER'
export const LOAD_MOVIE_YEAR = 'LOAD_MOVIE_YEAR'
export const LOAD_MOVIE_SORT_ASC = 'LOAD_MOVIE_SORT_ASC'
export const LOAD_MOVIE_SEARCH = 'LOAD_MOVIE_SEARCH'
